[CmdletBinding()]
param(
    [string] $CppPath,
    [string] $LlvmMcPath,
    [string] $ObjcopyPath,
    [string] $ObjdumpPath,
    [string] $PythonPath,
    [string] $OutputHeader,
    [string] $WorkDirectory
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Assert-Tool([string] $Name, [string] $Path) {
    if ([string]::IsNullOrWhiteSpace($Path) -or -not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "$Name was not found. Pass -${Name}Path with an explicit executable path."
    }
    return (Resolve-Path -LiteralPath $Path).Path
}

function Find-VisualCpp {
    $command = Get-Command cl.exe -ErrorAction SilentlyContinue
    if ($null -ne $command) {
        return $command.Source
    }

    $vswhere = 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe'
    if (Test-Path -LiteralPath $vswhere -PathType Leaf) {
        $candidate = & $vswhere -latest -products * `
            -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            -find 'VC\Tools\MSVC\**\bin\Hostx64\x64\cl.exe' |
            Select-Object -First 1
        if (-not [string]::IsNullOrWhiteSpace($candidate)) {
            return $candidate
        }
    }
    return $null
}

function Find-Python {
    foreach ($name in @('python3.exe', 'python.exe')) {
        $command = Get-Command $name -ErrorAction SilentlyContinue
        if ($null -eq $command) {
            continue
        }
        if ($command.Source -like '*\Microsoft\WindowsApps\python*.exe') {
            continue
        }
        & $command.Source -c 'import sys; print(sys.executable)' *> $null
        if ($LASTEXITCODE -eq 0) {
            return $command.Source
        }
    }
    return $null
}

function Get-Adler32([byte[]] $Data) {
    [uint32] $a = 1
    [uint32] $b = 0
    foreach ($value in $Data) {
        $a = ($a + $value) % 65521
        $b = ($b + $a) % 65521
    }
    return [uint32](([uint64]$b * 65536) + [uint64]$a)
}

function Get-Crc32([byte[]] $Data) {
    [uint64] $crc = 0xffffffffL
    foreach ($value in $Data) {
        $crc = ($crc -bxor [uint64]$value) -band 0xffffffffL
        for ($bit = 0; $bit -lt 8; ++$bit) {
            if (($crc -band 1) -ne 0) {
                $crc = (($crc -shr 1) -bxor 0xedb88320L) -band 0xffffffffL
            }
            else {
                $crc = $crc -shr 1
            }
        }
    }
    return [uint32](($crc -bxor 0xffffffffL) -band 0xffffffffL)
}

function Write-UncompressedStubHeader([string] $InputPath, [string] $HeaderPath) {
    [byte[]] $data = [IO.File]::ReadAllBytes($InputPath)
    $builder = [Text.StringBuilder]::new()
    [void]$builder.AppendLine('/* amd64-win64.pe.h')
    [void]$builder.AppendLine("   created from amd64-win64.pe-stripped.bin, $($data.Length) (0x$($data.Length.ToString('x'))) bytes")
    [void]$builder.AppendLine('')
    [void]$builder.AppendLine('   This file is part of the UPX executable compressor.')
    [void]$builder.AppendLine('   Generated by build-amd64-win64-modern.ps1.')
    [void]$builder.AppendLine(' */')
    [void]$builder.AppendLine('')
    [void]$builder.AppendLine("#define STUB_AMD64_WIN64_PE_SIZE    $($data.Length)")
    [void]$builder.AppendLine(('#define STUB_AMD64_WIN64_PE_ADLER32 0x{0:x8}' -f (Get-Adler32 $data)))
    [void]$builder.AppendLine(('#define STUB_AMD64_WIN64_PE_CRC32   0x{0:x8}' -f (Get-Crc32 $data)))
    [void]$builder.AppendLine('')
    [void]$builder.AppendLine("unsigned char stub_amd64_win64_pe[$($data.Length)] = {")
    for ($offset = 0; $offset -lt $data.Length; $offset += 16) {
        $end = [Math]::Min($offset + 16, $data.Length)
        $values = for ($index = $offset; $index -lt $end; ++$index) {
            $suffix = if ($index -ne $data.Length - 1) { ',' } else { '' }
            '{0,3}{1}' -f $data[$index], $suffix
        }
        [void]$builder.AppendLine(('/* 0x{0:x4} */ {1}' -f $offset, ($values -join '')))
    }
    [void]$builder.AppendLine('};')
    [IO.File]::WriteAllText($HeaderPath, $builder.ToString(), [Text.UTF8Encoding]::new($false))
}

$scriptDirectory = Split-Path -Parent $PSCommandPath
$stubDirectory = (Resolve-Path -LiteralPath (Join-Path $scriptDirectory '..')).Path
$repositoryRoot = (Resolve-Path -LiteralPath (Join-Path $stubDirectory '..\..')).Path
$workspaceRoot = (Resolve-Path -LiteralPath (Join-Path $repositoryRoot '..')).Path

if ([string]::IsNullOrWhiteSpace($CppPath)) {
    $CppPath = Find-VisualCpp
}
if ([string]::IsNullOrWhiteSpace($LlvmMcPath)) {
    $LlvmMcPath = Join-Path $workspaceRoot '.tools\llvm-msys\ucrt64\bin\llvm-mc.exe'
}
if ([string]::IsNullOrWhiteSpace($ObjcopyPath)) {
    $ObjcopyPath = Join-Path $workspaceRoot '.tools\msys\usr\bin\objcopy.exe'
}
if ([string]::IsNullOrWhiteSpace($ObjdumpPath)) {
    $ObjdumpPath = Join-Path $workspaceRoot '.tools\msys\usr\bin\objdump.exe'
}
if ([string]::IsNullOrWhiteSpace($PythonPath)) {
    $PythonPath = Find-Python
}
if ([string]::IsNullOrWhiteSpace($OutputHeader)) {
    $OutputHeader = Join-Path $stubDirectory 'amd64-win64.pe.h'
}
if ([string]::IsNullOrWhiteSpace($WorkDirectory)) {
    $WorkDirectory = Join-Path $stubDirectory 'tmp-modern\amd64-win64.pe'
}

$CppPath = Assert-Tool 'Cpp' $CppPath
$LlvmMcPath = Assert-Tool 'LlvmMc' $LlvmMcPath
$ObjcopyPath = Assert-Tool 'Objcopy' $ObjcopyPath
$ObjdumpPath = Assert-Tool 'Objdump' $ObjdumpPath
if (-not [string]::IsNullOrWhiteSpace($PythonPath)) {
    $PythonPath = Assert-Tool 'Python' $PythonPath
}

$source = (Resolve-Path -LiteralPath (Join-Path $stubDirectory 'src\amd64-win64.pe.S')).Path
$bin2h = (Resolve-Path -LiteralPath (Join-Path $scriptDirectory 'bin2h.py')).Path
$OutputHeader = [IO.Path]::GetFullPath($OutputHeader)
$WorkDirectory = [IO.Path]::GetFullPath($WorkDirectory)
[IO.Directory]::CreateDirectory($WorkDirectory) | Out-Null
[IO.Directory]::CreateDirectory((Split-Path -Parent $OutputHeader)) | Out-Null

$preprocessed = Join-Path $WorkDirectory 'amd64-win64.pe.i'
$object = Join-Path $WorkDirectory 'amd64-win64.pe.o'
$strippedObject = Join-Path $WorkDirectory 'amd64-win64.pe-stripped.o'
$dump = Join-Path $WorkDirectory 'amd64-win64.pe-stripped.dump'
$combined = Join-Path $WorkDirectory 'amd64-win64.pe-stripped.bin'

& $CppPath '/nologo' '/P' ("/Fi{0}" -f $preprocessed) '/TC' '/DWINDOWS_BACK=1' $source
if ($LASTEXITCODE -ne 0) {
    throw "C preprocessor failed with exit code $LASTEXITCODE"
}

& $LlvmMcPath '--triple=x86_64-pc-linux-gnu' '--filetype=obj' '-o' $object $preprocessed
if ($LASTEXITCODE -ne 0) {
    throw "llvm-mc failed with exit code $LASTEXITCODE"
}

Copy-Item -LiteralPath $object -Destination $strippedObject -Force
& $ObjcopyPath '--strip-unneeded' '--keep-symbol=_start' '--keep-symbol=upx_main2' `
    '--keep-symbol=upx_so_main' $strippedObject
if ($LASTEXITCODE -ne 0) {
    throw "objcopy symbol stripping failed with exit code $LASTEXITCODE"
}

& $ObjcopyPath '-R' '.text' '-R' '.data' '-R' '.bss' '-R' '.riscv.attributes' `
    '-R' '.comment' '-R' '.note' '-R' '.note.GNU-stack' '-R' '.reginfo' `
    '-R' '.mdebug.eabi32' '-R' '.gcc_compiled_long32' $strippedObject
if ($LASTEXITCODE -ne 0) {
    throw "objcopy section stripping failed with exit code $LASTEXITCODE"
}

$dumpLines = @(& $ObjdumpPath '-htr' '-w' $strippedObject)
if ($LASTEXITCODE -ne 0) {
    throw "objdump failed with exit code $LASTEXITCODE"
}
if ($dumpLines.Count -eq 0) {
    throw 'objdump produced no loader metadata'
}

# Remove the absolute object path so the generated loader is reproducible from
# different checkout locations. GNU objdump can emit a blank line first, so
# normalize the first line that actually contains the file-format marker.
$formatLineFound = $false
for ($index = 0; $index -lt $dumpLines.Count; ++$index) {
    if ($dumpLines[$index] -match ':\s*file format\s+') {
        $dumpLines[$index] = $dumpLines[$index] -replace '^.*:\s*file format', 'file format'
        $formatLineFound = $true
        break
    }
}
if (-not $formatLineFound) {
    throw 'objdump output has no file-format marker'
}
$dumpText = ($dumpLines -join "`n") + "`n"
[IO.File]::WriteAllText($dump, $dumpText, [Text.Encoding]::ASCII)

Copy-Item -LiteralPath $strippedObject -Destination $combined -Force
$dumpBytes = [IO.File]::ReadAllBytes($dump)
$stream = [IO.File]::Open($combined, [IO.FileMode]::Append, [IO.FileAccess]::Write, [IO.FileShare]::None)
try {
    $stream.Write($dumpBytes, 0, $dumpBytes.Length)
}
finally {
    $stream.Dispose()
}

if (-not [string]::IsNullOrWhiteSpace($PythonPath)) {
    & $PythonPath $bin2h '--ident=stub_amd64_win64_pe' '--compress=0' $combined $OutputHeader
    if ($LASTEXITCODE -ne 0) {
        throw "bin2h.py failed with exit code $LASTEXITCODE"
    }
}
else {
    Write-Host 'Python not found; using the built-in PowerShell bin2h fallback.'
    Write-UncompressedStubHeader $combined $OutputHeader
}

$header = Get-Item -LiteralPath $OutputHeader
$hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $OutputHeader).Hash
Write-Host ("Generated {0} ({1} bytes, SHA-256 {2})" -f $header.FullName, $header.Length, $hash)
